version: '3.8'

services:
  # Microservice : Authentification
  auth-service:
    image: openjdk:17-jdk-slim
    container_name: auth-service
    volumes:
      - ./auth-service.jar:/app/auth-service.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - auth-db
    networks:
      - microservices-network

  # Base de données pour le service Authentification
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Microservice : User
  user-service:
    image: openjdk:17-jdk-slim
    container_name: user-service
    volumes:
      - ./user-service.jar:/app/user-service.jar
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - user-db
    networks:
      - microservices-network

  # Base de données pour le service User
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Microservice : Ajout des produits
  product-add-service:
    image: openjdk:17-jdk-slim
    container_name: product-add-service
    volumes:
      - ./product-add-service.jar:/app/product-add-service.jar
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - product-db
    networks:
      - microservices-network

  # Base de données pour le service Ajout des produits
  product-db:
    image: postgres:15
    container_name: product-db
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Microservice : Création de compte
  account-creation-service:
    image: openjdk:17-jdk-slim
    container_name: account-creation-service
    volumes:
      - ./account-creation-service.jar:/app/account-creation-service.jar
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-db:5432/account_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - account-db
    networks:
      - microservices-network

  # Base de données pour le service Création de compte
  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      - POSTGRES_DB=account_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - account-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Microservice : Impression de facture
  invoice-service:
    image: openjdk:17-jdk-slim
    container_name: invoice-service
    volumes:
      - ./invoice-service.jar:/app/invoice-service.jar
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=invoice-service
    networks:
      - microservices-network

  # Microservice : Gestion et formatage d'images
  image-service:
    image: openjdk:17-jdk-slim
    container_name: image-service
    volumes:
      - ./image-service.jar:/app/image-service.jar
    ports:
      - "8085:8085"
    environment:
      - SPRING_APPLICATION_NAME=image-service
    networks:
      - microservices-network

  # Microservice : Affichage des produits
  product-display-service:
    image: openjdk:17-jdk-slim
    container_name: product-display-service
    volumes:
      - ./product-display-service.jar:/app/product-display-service.jar
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - product-db
    networks:
      - microservices-network

volumes:
  auth-db-data:
  user-db-data:
  product-db-data:
  account-db-data:

networks:
  microservices-network:
    driver: bridge